<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
  <li>
    <div class="kredivo_widget">
      <img class="kredivo_tooltip" src="http://kredivo.com/tooltip/images/tooltip-banner.png">
      <div class="kredivo_iframe">
        <iframe style="position: absolute; left: 0px; z-index:999;" class="tooltip_iframe" id="tooltip_iframe" src="http://kredivo.com/tooltip/index.html" frameborder="0" height="329" width="496">
        </iframe>
      </div>
    </div>
  </li>
</ul>
